In [2]:
#sam cleaning/eda
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('../data/tess_oi.csv')

In [4]:
data_dict = pd.read_csv('../data/tess_oi_data_dictionary.csv')

In [5]:
df.head()

,rowid,toi,toipfx,tid,ctoi_alias,pl_pnum,tfopwg_disp,rastr,ra,raerr1,raerr2,decstr,dec,decerr1,decerr2,st_pmra,st_pmraerr1,st_pmraerr2,st_pmralim,st_pmrasymerr,st_pmdec,st_pmdecerr1,st_pmdecerr2,st_pmdeclim,st_pmdecsymerr,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidlim,pl_tranmidsymerr,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbpersymerr,pl_trandurh,pl_trandurherr1,pl_trandurherr2,pl_trandurhlim,pl_trandurhsymerr,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandeplim,pl_trandepsymerr,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,pl_radesymerr,pl_insol,pl_insolerr1,pl_insolerr2,pl_insollim,pl_insolsymerr,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtlim,pl_eqtsymerr,st_tmag,st_tmagerr1,st_tmagerr2,st_tmaglim,st_tmagsymerr,st_dist,st_disterr1,st_disterr2,st_distlim,st_distsymerr,st_teff,st_tefferr1,st_tefferr2,st_tefflim,st_teffsymerr,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_loggsymerr,st_rad,st_raderr1,st_raderr2,st_radlim,st_radsymerr,toi_created,rowupdate
0,1,1000.01,1000,50365310,5.036531e+07,1,PC,07h29m25.85s,112.357708,NaN,NaN,-12d41m45.46s,-12.695960,NaN,NaN,-5.964,0.085,-0.085,0.0,1.0,-0.076,0.072,-0.072,0.0,1.0,2458493.384,0.00387,-0.00387,0,1,2.17153,0.00068,-0.00068,0,1,1.937,0.230,-0.230,0,1,720.000000,1.406120,-1.406120,0,1,5.56480,0.338744,-0.338744,0,1,6563.750000,NaN,NaN,NaN,NaN,2507.0,NaN,NaN,NaN,NaN,9.604000,0.013,-0.013,0,1,485.735,11.9515,-11.9515,0,1,10249.0,264.7,-264.7,0,1,4.19,0.07,-0.07,0,1,2.17,0.07,-0.07,0,1,3/26/2019 13:55,10/30/2020 1:59
1,2,1001.01,1001,88863718,8.886372e+07,1,PC,08h10m19.31s,122.580465,NaN,NaN,-05d30m49.87s,-5.513852,NaN,NaN,-4.956,0.102,-0.102,0.0,1.0,-15.555,0.072,-0.072,0.0,1.0,2458492.839,0.00356,-0.00356,0,1,1.93217,0.00054,-0.00054,0,1,3.447,0.243,-0.243,0,1,980.000000,0.698388,-0.698388,0,1,5.80204,0.318932,-0.318932,0,1,5753.000000,NaN,NaN,NaN,NaN,2426.0,NaN,NaN,NaN,NaN,9.423440,0.006,-0.006,0,1,295.862,5.9100,-5.9100,0,1,7070.0,126.4,-126.4,0,1,4.03,0.09,-0.09,0,1,2.01,0.09,-0.09,0,1,3/26/2019 13:55,5/20/2020 16:00
2,3,1002.01,1002,124709665,1.247097e+08,1,PC,06h58m54.47s,104.726966,NaN,NaN,-10d34m49.64s,-10.580455,NaN,NaN,-1.462,0.206,-0.206,0.0,1.0,-2.249,0.206,-0.206,0.0,1.0,2458492.602,0.00113,-0.00113,0,1,1.86722,0.00016,-0.00016,0,1,1.926,0.122,-0.122,0,1,1630.000000,708.410000,-708.410000,0,1,51.16650,NaN,NaN,0,1,38023.400000,NaN,NaN,NaN,NaN,3890.0,NaN,NaN,NaN,NaN,9.299501,0.058,-0.058,0,1,943.109,106.3330,-106.3330,0,1,8924.0,124.0,-124.0,0,1,NaN,NaN,NaN,0,1,5.73,NaN,NaN,0,1,3/26/2019 13:55,10/30/2020 1:59
3,4,1003.01,1003,106997505,1.069975e+08,1,FP,07h22m14.39s,110.559945,NaN,NaN,-25d12m25.26s,-25.207017,NaN,NaN,-0.939,0.041,-0.041,0.0,1.0,1.640,0.055,-0.055,0.0,1.0,2458493.396,0.00535,-0.00535,0,1,2.74323,0.00108,-0.00108,0,1,3.167,0.642,-0.642,0,1,383.410004,0.781988,-0.781988,0,1,NaN,NaN,NaN,0,1,1177.359985,NaN,NaN,NaN,NaN,1631.0,NaN,NaN,NaN,NaN,9.300300,0.037,-0.037,0,1,7728.170,1899.5700,-1899.5700,0,1,5388.5,567.0,-567.0,0,1,4.15,1.64,-1.64,0,1,NaN,NaN,NaN,0,1,3/26/2019 13:55,12/17/2019 10:00
4,5,1004.01,1004,238597883,2.385979e+08,1,PC,08h08m42.77s,122.178195,NaN,NaN,-48d48m10.12s,-48.802811,NaN,NaN,-4.496,0.069,-0.069,0.0,1.0,9.347,0.062,-0.062,0.0,1.0,2458493.512,0.00653,-0.00653,0,1,3.57491,0.00146,-0.00146,0,1,2.576,0.346,-0.346,0,1,500.000000,1.079660,-1.079660,0,1,4.75276,0.279769,-0.279769,0,1,2929.870000,NaN,NaN,NaN,NaN,2049.0,NaN,NaN,NaN,NaN,9.135500,0.006,-0.006,0,1,356.437,4.6175,-4.6175,0,1,9219.0,171.1,-171.1,0,1,4.14,0.07,-0.07,0,1,2.15,0.06,-0.06,0,1,3/26/2019 13:55,10/30/2020 1:59

In [6]:
df.shape

(2542, 87)

In [7]:
data_dict

                                # COLUMN toi:            TESS Object of Interest
0                        # COLUMN toipfx:         TESS Object of Interest Prefix
1                                 # COLUMN tid:            TESS Input Catalog ID
2               # COLUMN ctoi_alias:     Community TESS Object of Interest Alias
3                                    # COLUMN pl_pnum:        Pipeline Signal ID
4                 # COLUMN tfopwg_disp:    TFOPWG Dispostion (CP | FP | KP | PC)
5                                      # COLUMN rastr:          RA [sexagesimal]
6                                              # COLUMN ra:             RA [deg]
7                                          # COLUMN raerr1:         RA Upper Unc
8                                          # COLUMN raerr2:         RA Lower Unc
9                                     # COLUMN decstr:         Dec [sexagesimal]
10                                            # COLUMN dec:            Dec [deg]
11                                        # COLUMN decerr1:        Dec Upper Unc
12                                        # COLUMN decerr2:        Dec Lower Unc
13                                        # COLUMN st_pmra:        PMRA [mas/yr]
14                              # COLUMN st_pmraerr1:    PMRA Upper Unc [mas/yr]
15                              # COLUMN st_pmraerr2:    PMRA Lower Unc [mas/yr]
16                                      # COLUMN st_pmralim:     PMRA Limit Flag
17                            # COLUMN st_pmrasymerr:  PMRA Symmetric Error Flag
18                                       # COLUMN st_pmdec:       PMDec [mas/yr]
19                             # COLUMN st_pmdecerr1:   PMDec Upper Unc [mas/yr]
20                             # COLUMN st_pmdecerr2:   PMDec Lower Unc [mas/yr]
21                                     # COLUMN st_pmdeclim:    PMDec Limit Flag
22                           # COLUMN st_pmdecsymerr: PMDec Symmetric Error Flag
23                  # COLUMN pl_tranmid:     Planet Transit Midpoint Value [BJD]
24              # COLUMN pl_tranmiderr1: Planet Transit Midpoint Upper Unc [BJD]
25              # COLUMN pl_tranmiderr2: Planit Transit Midpoint Lower Unc [BJD]
26                   # COLUMN pl_tranmidlim:  Planet Transit Midpoint Limit Flag
27       # COLUMN pl_tranmidsymerr: Planet Transit Midpoint Symmetric Error Flag
28                   # COLUMN pl_orbper:      Planet Orbital Period Value [days]
29               # COLUMN pl_orbpererr1:  Planet Orbital Period Upper Unc [days]
30               # COLUMN pl_orbpererr2:  Planet Orbital Period Lower Unc [days]
31                     # COLUMN pl_orbperlim:   Planet Orbital Period Limit Flag
32          # COLUMN pl_orbpersymerr: Planet Orbital Period Symmetric Error Flag
33                # COLUMN pl_trandurh:    Planet Transit Duration Value [hours]
34           # COLUMN pl_trandurherr1: Planet Transit Duration Upper Unc [hours]
35           # COLUMN pl_trandurherr2: Planet Transit Duration Lower Unc [hours]
36                   # COLUMN pl_trandurhlim: Planet Transit Duration Limit Flag
37      # COLUMN pl_trandurhsymerr: Planet Transit Duration Symmetric Error Flag
38                     # COLUMN pl_trandep:     Planet Transit Depth Value [ppm]
39                 # COLUMN pl_trandeperr1: Planet Transit Depth Upper Unc [ppm]
40                 # COLUMN pl_trandeperr2: Planet Transit Depth Lower Unc [ppm]
41                      # COLUMN pl_trandeplim:  Planet Transit Depth Limit Flag
42          # COLUMN pl_trandepsymerr: Planet Transit Depth Symmetric Error Flag
43                        # COLUMN pl_rade:        Planet Radius Value [R_Earth]
44                    # COLUMN pl_radeerr1:    Planet Radius Upper Unc [R_Earth]
45                    # COLUMN pl_radeerr2:    Planet Radius Lower Unc [R_Earth]
46                             # COLUMN pl_radelim:     Planet Radius Limit Flag
47                   # COLUMN pl_radesymerr:  Planet Radius Symmetric Error Flag
48                 # COLUMN pl_insol:       Planet Insolation Value [Earth flux]
49             # COLUMN pl_insolerr1:   Planet Insolation Upper Unc [Earth flux]
50             # COLUMN pl_insolerr2:   Planet Insolation Lower Unc [Earth flux]
51                         # COLUMN pl_insollim:    Planet Insolation Limit Flag
52               # COLUMN pl_insolsymerr: Planet Insolation Symmetric Error Flag
53             # COLUMN pl_eqt:         Planet Equilibrium Temperature Value [K]
54         # COLUMN pl_eqterr1:     Planet Equilibrium Temperature Upper Unc [K]
55         # COLUMN pl_eqterr2:     Planet Equilibrium Temperature Lower Unc [K]
56            # COLUMN pl_eqtlim:      Planet Equilibrium Temperature Limit Flag
57  # COLUMN pl_eqtsymerr:   Planet Equilibrium Temperature Symmetric Error Flag
58                                       # COLUMN st_tmag:        TESS Magnitude
59                             # COLUMN st_tmagerr1:    TESS Magnitude Upper Unc
60                             # COLUMN st_tmagerr2:    TESS Magnitude Lower Unc
61                            # COLUMN st_tmaglim:     TESS Magnitude Limit Flag
62                  # COLUMN st_tmagsymerr:  TESS Magnitude Symmetric Error Flag
63                                # COLUMN st_dist:        Stellar Distance [pc]
64                      # COLUMN st_disterr1:    Stellar Distance Upper Unc [pc]
65                      # COLUMN st_disterr2:    Stellar Distance Lower Unc [pc]
66                          # COLUMN st_distlim:     Stellar Distance Limit Flag
67                # COLUMN st_distsymerr:  Stellar Distance Symmetric Error Flag
68              # COLUMN st_teff:        Stellar Effective Temperature Value [K]
69         # COLUMN st_tefferr1:    Stellar Effective Termperature Upper Unc [K]
70          # COLUMN st_tefferr2:    Stellar Effective Temperature Lower Unc [K]
71             # COLUMN st_tefflim:     Stellar Effective Temperature Limit Flag
72   # COLUMN st_teffsymerr:  Stellar Effective Temperature Symmetric Error Flag
73                       # COLUMN st_logg:        Stellar log(g) Value [cm/s**2]
74                    # COLUMN st_loggerr1:    Stellar log(g) Upper Unc [cm/s**]
75                   # COLUMN st_loggerr2:    Stellar log(g) Lower Unc [cm/s**2]
76                            # COLUMN st_logglim:     Stellar log(g) Limit Flag
77                  # COLUMN st_loggsymerr:  Stellar log(g) Symmetric Error Flag
78                         # COLUMN st_rad:         Stellar Radius Value [R_Sun]
79                     # COLUMN st_raderr1:     Stellar Radius Upper Unc [R_Sun]
80                     # COLUMN st_raderr2:     Stellar Radius Lower Unc [R_Sun]
81                            # COLUMN st_radlim:      Stellar Radius Limit Flag
82                  # COLUMN st_radsymerr:   Stellar Radius Symmetric Error Flag
83                                     # COLUMN toi_created:    TOI Created Date
84                                        # COLUMN rowupdate:      Date Modified
85                                                                             #

In [8]:
df.isna().sum()

rowid                   0
toi                     0
toipfx                  0
tid                     0
ctoi_alias              0
pl_pnum                 0
tfopwg_disp             7
rastr                   0
ra                      0
raerr1               2542
raerr2               2542
decstr                  0
dec                     0
decerr1              2542
decerr2              2542
st_pmra                16
st_pmraerr1            16
st_pmraerr2            16
st_pmralim             16
st_pmrasymerr          16
st_pmdec               16
st_pmdecerr1           16
st_pmdecerr2           16
st_pmdeclim            16
st_pmdecsymerr         16
pl_tranmid              0
pl_tranmiderr1         21
pl_tranmiderr2         21
pl_tranmidlim           0
pl_tranmidsymerr        0
pl_orbper              79
pl_orbpererr1         116
pl_orbpererr2         116
pl_orbperlim            0
pl_orbpersymerr         0
pl_trandurh             0
pl_trandurherr1         7
pl_trandurherr2         7
pl_trandurhlim          0
pl_trandurhsymerr       0
pl_trandep              0
pl_trandeperr1         14
pl_trandeperr2         14
pl_trandeplim           0
pl_trandepsymerr        0
pl_rade               132
pl_radeerr1           262
pl_radeerr2           262
pl_radelim              0
pl_radesymerr           0
pl_insol              131
pl_insolerr1         2542
pl_insolerr2         2542
pl_insollim          2542
pl_insolsymerr       2542
pl_eqt                164
pl_eqterr1           2542
pl_eqterr2           2542
pl_eqtlim            2542
pl_eqtsymerr         2542
st_tmag                 0
st_tmagerr1             0
st_tmagerr2             0
st_tmaglim              0
st_tmagsymerr           0
st_dist                50
st_disterr1           169
st_disterr2           169
st_distlim              0
st_distsymerr           0
st_teff                36
st_tefferr1           227
st_tefferr2           227
st_tefflim              0
st_teffsymerr           0
st_logg               245
st_loggerr1           533
st_loggerr2           533
st_logglim              0
st_loggsymerr           0
st_rad                133
st_raderr1            403
st_raderr2            403
st_radlim               0
st_radsymerr            0
toi_created             0
rowupdate               0
dtype: int64

In [9]:
df.dtypes

rowid                  int64
toi                  float64
toipfx                 int64
tid                    int64
ctoi_alias           float64
pl_pnum                int64
tfopwg_disp           object
rastr                 object
ra                   float64
raerr1               float64
raerr2               float64
decstr                object
dec                  float64
decerr1              float64
decerr2              float64
st_pmra              float64
st_pmraerr1          float64
st_pmraerr2          float64
st_pmralim           float64
st_pmrasymerr        float64
st_pmdec             float64
st_pmdecerr1         float64
st_pmdecerr2         float64
st_pmdeclim          float64
st_pmdecsymerr       float64
pl_tranmid           float64
pl_tranmiderr1       float64
pl_tranmiderr2       float64
pl_tranmidlim          int64
pl_tranmidsymerr       int64
pl_orbper            float64
pl_orbpererr1        float64
pl_orbpererr2        float64
pl_orbperlim           int64
pl_orbpersymerr        int64
pl_trandurh          float64
pl_trandurherr1      float64
pl_trandurherr2      float64
pl_trandurhlim         int64
pl_trandurhsymerr      int64
pl_trandep           float64
pl_trandeperr1       float64
pl_trandeperr2       float64
pl_trandeplim          int64
pl_trandepsymerr       int64
pl_rade              float64
pl_radeerr1          float64
pl_radeerr2          float64
pl_radelim             int64
pl_radesymerr          int64
pl_insol             float64
pl_insolerr1         float64
pl_insolerr2         float64
pl_insollim          float64
pl_insolsymerr       float64
pl_eqt               float64
pl_eqterr1           float64
pl_eqterr2           float64
pl_eqtlim            float64
pl_eqtsymerr         float64
st_tmag              float64
st_tmagerr1          float64
st_tmagerr2          float64
st_tmaglim             int64
st_tmagsymerr          int64
st_dist              float64
st_disterr1          float64
st_disterr2          float64
st_distlim             int64
st_distsymerr          int64
st_teff              float64
st_tefferr1          float64
st_tefferr2          float64
st_tefflim             int64
st_teffsymerr          int64
st_logg              float64
st_loggerr1          float64
st_loggerr2          float64
st_logglim             int64
st_loggsymerr          int64
st_rad               float64
st_raderr1           float64
st_raderr2           float64
st_radlim              int64
st_radsymerr           int64
toi_created           object
rowupdate             object
dtype: object

-Imputing Nulls-

In [10]:
#dropping everything that has over half the dataset as null
df = df.dropna(axis = 1, thresh= 1271)

In [11]:
df.isna().sum()

rowid                  0
toi                    0
toipfx                 0
tid                    0
ctoi_alias             0
pl_pnum                0
tfopwg_disp            7
rastr                  0
ra                     0
decstr                 0
dec                    0
st_pmra               16
st_pmraerr1           16
st_pmraerr2           16
st_pmralim            16
st_pmrasymerr         16
st_pmdec              16
st_pmdecerr1          16
st_pmdecerr2          16
st_pmdeclim           16
st_pmdecsymerr        16
pl_tranmid             0
pl_tranmiderr1        21
pl_tranmiderr2        21
pl_tranmidlim          0
pl_tranmidsymerr       0
pl_orbper             79
pl_orbpererr1        116
pl_orbpererr2        116
pl_orbperlim           0
pl_orbpersymerr        0
pl_trandurh            0
pl_trandurherr1        7
pl_trandurherr2        7
pl_trandurhlim         0
pl_trandurhsymerr      0
pl_trandep             0
pl_trandeperr1        14
pl_trandeperr2        14
pl_trandeplim          0
pl_trandepsymerr       0
pl_rade              132
pl_radeerr1          262
pl_radeerr2          262
pl_radelim             0
pl_radesymerr          0
pl_insol             131
pl_eqt               164
st_tmag                0
st_tmagerr1            0
st_tmagerr2            0
st_tmaglim             0
st_tmagsymerr          0
st_dist               50
st_disterr1          169
st_disterr2          169
st_distlim             0
st_distsymerr          0
st_teff               36
st_tefferr1          227
st_tefferr2          227
st_tefflim             0
st_teffsymerr          0
st_logg              245
st_loggerr1          533
st_loggerr2          533
st_logglim             0
st_loggsymerr          0
st_rad               133
st_raderr1           403
st_raderr2           403
st_radlim              0
st_radsymerr           0
toi_created            0
rowupdate              0
dtype: int64

In [12]:
#drop all error columns and limit columns
df = df.drop(columns = [column for column in df.columns if 'err' in column])
df = df.drop(columns = [column for column in df.columns if 'lim' in column])

In [13]:
df.isna().sum()

rowid            0
toi              0
toipfx           0
tid              0
ctoi_alias       0
pl_pnum          0
tfopwg_disp      7
rastr            0
ra               0
decstr           0
dec              0
st_pmra         16
st_pmdec        16
pl_tranmid       0
pl_orbper       79
pl_trandurh      0
pl_trandep       0
pl_rade        132
pl_insol       131
pl_eqt         164
st_tmag          0
st_dist         50
st_teff         36
st_logg        245
st_rad         133
toi_created      0
rowupdate        0
dtype: int64

In [14]:
#pad the nulls out to 20, and impute the mean beyond that limit.
df = df.fillna(method = 'pad', limit = 20)
df = df.fillna(df.mean())

In [15]:
df.isna().sum()

rowid          0
toi            0
toipfx         0
tid            0
ctoi_alias     0
pl_pnum        0
tfopwg_disp    0
rastr          0
ra             0
decstr         0
dec            0
st_pmra        0
st_pmdec       0
pl_tranmid     0
pl_orbper      0
pl_trandurh    0
pl_trandep     0
pl_rade        0
pl_insol       0
pl_eqt         0
st_tmag        0
st_dist        0
st_teff        0
st_logg        0
st_rad         0
toi_created    0
rowupdate      0
dtype: int64

In [16]:
df.to_csv('../data/cleaned.csv', index= False)

In [17]:
df.head()

,rowid,toi,toipfx,tid,ctoi_alias,pl_pnum,tfopwg_disp,rastr,ra,decstr,dec,st_pmra,st_pmdec,pl_tranmid,pl_orbper,pl_trandurh,pl_trandep,pl_rade,pl_insol,pl_eqt,st_tmag,st_dist,st_teff,st_logg,st_rad,toi_created,rowupdate
0,1,1000.01,1000,50365310,5.036531e+07,1,PC,07h29m25.85s,112.357708,-12d41m45.46s,-12.695960,-5.964,-0.076,2458493.384,2.17153,1.937,720.000000,5.56480,6563.750000,2507.0,9.604000,485.735,10249.0,4.19,2.17,3/26/2019 13:55,10/30/2020 1:59
1,2,1001.01,1001,88863718,8.886372e+07,1,PC,08h10m19.31s,122.580465,-05d30m49.87s,-5.513852,-4.956,-15.555,2458492.839,1.93217,3.447,980.000000,5.80204,5753.000000,2426.0,9.423440,295.862,7070.0,4.03,2.01,3/26/2019 13:55,5/20/2020 16:00
2,3,1002.01,1002,124709665,1.247097e+08,1,PC,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,-1.462,-2.249,2458492.602,1.86722,1.926,1630.000000,51.16650,38023.400000,3890.0,9.299501,943.109,8924.0,4.03,5.73,3/26/2019 13:55,10/30/2020 1:59
3,4,1003.01,1003,106997505,1.069975e+08,1,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,-0.939,1.640,2458493.396,2.74323,3.167,383.410004,51.16650,1177.359985,1631.0,9.300300,7728.170,5388.5,4.15,5.73,3/26/2019 13:55,12/17/2019 10:00
4,5,1004.01,1004,238597883,2.385979e+08,1,PC,08h08m42.77s,122.178195,-48d48m10.12s,-48.802811,-4.496,9.347,2458493.512,3.57491,2.576,500.000000,4.75276,2929.870000,2049.0,9.135500,356.437,9219.0,4.14,2.15,3/26/2019 13:55,10/30/2020 1:59

In [18]:
df.dtypes

rowid            int64
toi            float64
toipfx           int64
tid              int64
ctoi_alias     float64
pl_pnum          int64
tfopwg_disp     object
rastr           object
ra             float64
decstr          object
dec            float64
st_pmra        float64
st_pmdec       float64
pl_tranmid     float64
pl_orbper      float64
pl_trandurh    float64
pl_trandep     float64
pl_rade        float64
pl_insol       float64
pl_eqt         float64
st_tmag        float64
st_dist        float64
st_teff        float64
st_logg        float64
st_rad         float64
toi_created     object
rowupdate       object
dtype: object

In [19]:
#casual initial model to see how it compares to a baseline

In [20]:
#turn the classification labels into numbers
tfop_dict = {'FP': 0, 'CP': 1, 'PC':1,'KP':1,'APC':0,'FA':0}
df['tfopwg_num'] = df['tfopwg_disp'].map(tfop_dict)

In [21]:
df['tfopwg_disp'].head()

0    PC
1    PC
2    PC
3    FP
4    PC
Name: tfopwg_disp, dtype: object

In [22]:
df['tfopwg_num'].head()

0    1
1    1
2    1
3    0
4    1
Name: tfopwg_num, dtype: int64

In [23]:
to_drop = ['rowid','toi','toipfx','tid','ctoi_alias','tfopwg_disp','tfopwg_num','rastr','decstr','toi_created','rowupdate']

In [24]:
X = df.drop(columns = to_drop)
y = df['tfopwg_num']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.fit_transform(X_test)

In [25]:
model = LogisticRegression()

In [26]:
model.fit(X_train_sc, y_train)

LogisticRegression()

In [27]:
X_train_sc.shape

(1906, 17)

In [28]:
baseline = np.random.randint(low = 0, high = 2, size = X_train_sc.shape[0])

In [29]:
print(model.score(X_train_sc, y_train))
print(model.score(X_test_sc, y_test))
print(model.score(X_train_sc, baseline))

0.7586568730325288
0.7641509433962265
0.4926547743966422

In [30]:
#pretty good!  Could be better,but I like those odds right out of the gate.  We'll see in the other notebook if we can do better.